name: CI

on: [push]

jobs:
  build:
    name: Python ${{ matrix.python-version }} environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Cache .tox folder
        uses: actions/cache@v1
        with:
          path: .tox
          key: tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements.txt') }}

      - name: Run tests
        run: tox -e flake8

  auto-pull-request:
    name: Auto PR
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feature/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_DRAFT: true
